version: '3.1'
services:
  server:
    image: "igvir/nodejs-mongo-client:v0.0.7-beta"
    container_name: serverRanking
    networks:
      - ranking-net
    environment:
      DB_HOST: "db"
      DB_USERNAME: ${MONGODB_USER}
      DB_PASSWORD: ${MONGODB_PASSWORD}
      DB_TYPE: "mongodb"
      DB_NAME: ${MONGODB_DATABASE}
      DB_WITHUSERCREDENTIALS: ${MONGODB_DATABASE} 
      AWS_ACCESS_KEY_ID: ${AWS_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_KEY}
      AWS_REGION: ${AWS_REGION}
      
    depends_on:
      - db
    links:
      - db

  db:
    container_name: rankingDB
    image: registry.access.redhat.com/rhscl/mongodb-36-rhel7 
    environment:
      MONGODB_ADMIN_PASSWORD: ${MONGODB_ADMIN_PASSWORD}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    networks:
      - ranking-net

networks:
  ranking-net:

          
