version: '3.1'
services:
  server:
    image: "igvir/nodejs-mongo-client:v0.0.6-beta"
    container_name: serverRanking
    networks:
      - ranking-net
    environment:
      DB_HOST: "db"
      DB_USERNAME: "dbUser"
      DB_PASSWORD: "dbUser7890pwd"
      DB_TYPE: "mongodb"
      DB_NAME: "leaderboard_db"
      AWS_ACCESS_KEY_ID: "A"
      AWS_SECRET_ACCESS_KEY: ""
      AWS_REGION: "us-west-2"
    secrets:
      - db_pwd
      - aws_id
      - aws_key      
    depends_on:
      - db
    links:
      - db

  db:
    container_name: rankingDB
    image: registry.access.redhat.com/rhscl/mongodb-36-rhel7 
    environment:
      MONGODB_ADMIN_PASSWORD: "ranking-1234Admin"
      MONGODB_USER: "dbUser"
      MONGODB_PASSWORD: "dbUser7890pwd"
      MONGODB_DATABASE: "leaderboard_db"
    secrets:
      - db_admin_pwd      
    networks:
      - ranking-net

networks:
  ranking-net:

          
secrets: 
  db_pwd:
      file: ./db_pwd.ignore.txt
  db_admin_pwd:
      file: ./db_admin_pwd.ignore.txt    
  aws_id:
      file: ./aws_id.ignore.txt
  aws_key:
      file: ./aws_key.ignore.txt

