version: '3.0'
services:
  server:
    image: igvir/nodejs-mongo-client
    container_name: serverRanking
    networks:
      - ranking-net
    depends_on:
      - db
    links:
      - db
  db:
    container_name: rankingDB
    image: registry.access.redhat.com/rhscl/mongodb-36-rhel7 
    environment:
      MONGODB_ADMIN_PASSWORD: "ranking-1234Admin"
      MONGODB_USER: ""
      MONGODB_PASSWORD: ""
      MONGODB_DATABASE: "leaderboard_db"
    networks:
      - ranking-net

networks:
  ranking-net:
 
